# Created using wingetcreate

PackageIdentifier: RockstarGames.Launcher
PackageVersion: 2.0.81
PackageLocale: en-US
Publisher: Rockstar Games
PackageName: Rockstar Games Launcher
License: Rockstar Games Inc. (C) 2005-2019 Take Two Interactive. All rights reserved
ShortDescription: Rockstar Games Launcher
ManifestType: defaultLocale
ManifestVersion: 1.0.0
